version: '3.7'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: evabuysell

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    